version: '3.9'

services:
  node-app:
    build: .
    ports:
      - "9001:9001"
    volumes:
      - "/home/fedora/CodeArea/ITI/nodejs/vol:/root"
    networks:
      - node-network
  mongo:
    image: "mongo:latest"
    volumes:
      - "/home/fedora/CodeArea/ITI/mongodb/volumes/db:/data/db"
    networks:
      - node-network

networks:
   node-network: 